site_name: pywassap
site_description: A simple FastAPI wrapper for WhatsApp Web API.
site_url: https://pywassap.netlify.app/
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: Aarif1430/pywassap
repo_url: https://github.com/Aarif1430/pywassap
edit_uri: ""
nav:
  - Home: index.md
  - Features - User Guide:
      - sections/index.md
  - release.md
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include

extra:
  analytics:
    provider: google
    property: UA-216293837-1
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Aarif1430
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MalikAarif1430
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/maarif1430/

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
